### ISSUE TITLE
d.ts result Minimap dose not export

### ISSUE THREAD

**Issue by FocusCare** [awslabs/diagram-maker-plugin-minimap#23]
**Describe the bug**
in diagramMakerMinimap.d.ts

declare class Minimap<NodeType, EdgeType> extends React.Component<MinimapProps<NodeType, EdgeType>> {
	render(): JSX.Element | undefined;
	private getCanvasSize;
	private getMinimapNode;
	private renderMinimapNodes;
}

Minimap dose not export

**To Reproduce**
1. typescript import Minimap from this package

**Expected behavior**
in d.ts export Minimap

**Screenshots**
![image](https://user-images.githubusercontent.com/3634726/114137270-81d25780-993e-11eb-9216-6335447b6b7b.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser chrome
 - Version 89

**Additional context**
none

**Comment by ashika01** [comment]
Could you verify after using the latest version? Looks like it should have been fixed now. Feel free to close the ticket if its all good.

**Comment by ashika01** [comment]
Closing this issue because this has been stale over weeks now. If this remains to be an issue, let us know and we will reopen this issue.
