### ISSUE TITLE
Update peer-dependencies and push to npm registry

### ISSUE THREAD

**Issue by alex59495** [awslabs/diagram-maker-plugin-minimap#60]
**Is your feature request related to a problem? Please describe.**

I am currently wanting to use this package on a project using the last version of : 
- react 17.0.x
- diagram-maker 1.3.x. 

The last version pushed to npm was 2 years ago and still reference as peer dependencies :
- react 16.8.x
- react-dom 16.8.x
- diagramMaker 1.0.0 (there is an error on the name, which cannot be camelcase anymore. It was resolved on the master but not pushed to the npm registry)

**Describe the solution you'd like**
Update peer-dependencies to be able to use the last version of React and diagramMaker and push it to the npm registry.

**More context**
Actually I was already using the package (thank you for the great work you've done on it !) with node 14 and npm 6. I recently updated to node 16 and npm 8 and now it is pointing out that I have some peer-dependencies issues, as I said above.

I could still bypass this error by running a `npm install --legacy-peer-deps` but I think it would be nice to have those updates done in order to keep the project up to date :)

Thanks for the help !

**Comment by NorbertNader** [comment]
Thank you for opening this issue @alex59495 !

Our team will take a look at this and we will get back to you with updates on this as soon as possible.

I think you are right and we should publish a new version.

**Comment by NorbertNader** [comment]
Hey @alex59495,

We just published version 1.0.1 to npm  https://www.npmjs.com/package/diagram-maker-plugin-minimap

**Comment by alex59495** [comment]
It works like a charm, thanks a lot for the reactivity !
